In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
imb = pd.read_csv(r'C:\Users\ANKIT\Desktop\DATA ANALYSIST\DATASETS\creditcard.csv')
imb.head(40)

Time        V1        V2        V3        V4        V5        V6  \
0    0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388   
1    0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361   
2    1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499   
3    1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203   
4    2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921   
5    2.0 -0.425966  0.960523  1.141109 -0.168252  0.420987 -0.029728   
6    4.0  1.229658  0.141004  0.045371  1.202613  0.191881  0.272708   
7    7.0 -0.644269  1.417964  1.074380 -0.492199  0.948934  0.428118   
8    7.0 -0.894286  0.286157 -0.113192 -0.271526  2.669599  3.721818   
9    9.0 -0.338262  1.119593  1.044367 -0.222187  0.499361 -0.246761   
10  10.0  1.449044 -1.176339  0.913860 -1.375667 -1.971383 -0.629152   
11  10.0  0.384978  0.616109 -0.874300 -0.094019  2.924584  3.317027   
12  10.0  1.249999 -1.221637  0.383930 -1.234899 -1.485419 -0.753230   
13  11.0  1.069374  0.287722  0.828613  2.712520 -0.178398  0.337544   
14  12.0 -2.791855 -0.327771  1.641750  1.767473 -0.136588  0.807596   
15  12.0 -0.752417  0.345485  2.057323 -1.468643 -1.158394 -0.077850   
16  12.0  1.103215 -0.040296  1.267332  1.289091 -0.735997  0.288069   
17  13.0 -0.436905  0.918966  0.924591 -0.727219  0.915679 -0.127867   
18  14.0 -5.401258 -5.450148  1.186305  1.736239  3.049106 -1.763406   
19  15.0  1.492936 -1.029346  0.454795 -1.438026 -1.555434 -0.720961   
20  16.0  0.694885 -1.361819  1.029221  0.834159 -1.191209  1.309109   
21  17.0  0.962496  0.328461 -0.171479  2.109204  1.129566  1.696038   
22  18.0  1.166616  0.502120 -0.067300  2.261569  0.428804  0.089474   
23  18.0  0.247491  0.277666  1.185471 -0.092603 -1.314394 -0.150116   
24  22.0 -1.946525 -0.044901 -0.405570 -1.013057  2.941968  2.955053   
25  22.0 -2.074295 -0.121482  1.322021  0.410008  0.295198 -0.959537   
26  23.0  1.173285  0.353498  0.283905  1.133563 -0.172577 -0.916054   
27  23.0  1.322707 -0.174041  0.434555  0.576038 -0.836758 -0.831083   
28  23.0 -0.414289  0.905437  1.727453  1.473471  0.007443 -0.200331   
29  23.0  1.059387 -0.175319  1.266130  1.186110 -0.786002  0.578435   
30  24.0  1.237429  0.061043  0.380526  0.761564 -0.359771 -0.494084   
31  25.0  1.114009  0.085546  0.493702  1.335760 -0.300189 -0.010754   
32  26.0 -0.529912  0.873892  1.347247  0.145457  0.414209  0.100223   
33  26.0 -0.529912  0.873892  1.347247  0.145457  0.414209  0.100223   
34  26.0 -0.535388  0.865268  1.351076  0.147575  0.433680  0.086983   
35  26.0 -0.535388  0.865268  1.351076  0.147575  0.433680  0.086983   
36  27.0 -0.246046  0.473267  1.695738  0.262411 -0.010866 -0.610836   
37  27.0 -1.452187  1.765124  0.611669  1.176825 -0.445980  0.246826   
38  29.0  0.996370 -0.122589  0.546819  0.706580  0.134560  1.156995   
39  29.0  1.110880  0.168717  0.517144  1.325407 -0.191573  0.019504   

          V7        V8        V9  ...       V21       V22       V23       V24  \
0   0.239599  0.098698  0.363787  ... -0.018307  0.277838 -0.110474  0.066928   
1  -0.078803  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288 -0.339846   
2   0.791461  0.247676 -1.514654  ...  0.247998  0.771679  0.909412 -0.689281   
3   0.237609  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321 -1.175575   
4   0.592941 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458  0.141267   
5   0.476201  0.260314 -0.568671  ... -0.208254 -0.559825 -0.026398 -0.371427   
6  -0.005159  0.081213  0.464960  ... -0.167716 -0.270710 -0.154104 -0.780055   
7   1.120631 -3.807864  0.615375  ...  1.943465 -1.015455  0.057504 -0.649709   
8   0.370145  0.851084 -0.392048  ... -0.073425 -0.268092 -0.204233  1.011592   
9   0.651583  0.069539 -0.736727  ... -0.246914 -0.633753 -0.120794 -0.385050   
10 -1.423236  0.048456 -1.720408  ... -0.009302  0.313894  0.027740  0.500512   
11  0.470455  0.538247 -0.558895  ...  0.049924  0.238422  0.009130  0.996710  

In [ ]:
imb.info()

In [ ]:
imb.isnull().sum()

In [ ]:
imb.shape

In [4]:
imb['Class'].value_counts()

0    284315
1       492
Name: Class, dtype: int64

In [5]:
x = imb.drop('Class',axis = 1)
y = imb['Class']

In [6]:
x

Time         V1         V2        V3        V4        V5  \
0            0.0  -1.359807  -0.072781  2.536347  1.378155 -0.338321   
1            0.0   1.191857   0.266151  0.166480  0.448154  0.060018   
2            1.0  -1.358354  -1.340163  1.773209  0.379780 -0.503198   
3            1.0  -0.966272  -0.185226  1.792993 -0.863291 -0.010309   
4            2.0  -1.158233   0.877737  1.548718  0.403034 -0.407193   
...          ...        ...        ...       ...       ...       ...   
284802  172786.0 -11.881118  10.071785 -9.834783 -2.066656 -5.364473   
284803  172787.0  -0.732789  -0.055080  2.035030 -0.738589  0.868229   
284804  172788.0   1.919565  -0.301254 -3.249640 -0.557828  2.630515   
284805  172788.0  -0.240440   0.530483  0.702510  0.689799 -0.377961   
284806  172792.0  -0.533413  -0.189733  0.703337 -0.506271 -0.012546   

              V6        V7        V8        V9  ...       V20       V21  \
0       0.462388  0.239599  0.098698  0.363787  ...  0.251412 -0.018307   
1      -0.082361 -0.078803  0.085102 -0.255425  ... -0.069083 -0.225775   
2       1.800499  0.791461  0.247676 -1.514654  ...  0.524980  0.247998   
3       1.247203  0.237609  0.377436 -1.387024  ... -0.208038 -0.108300   
4       0.095921  0.592941 -0.270533  0.817739  ...  0.408542 -0.009431   
...          ...       ...       ...       ...  ...       ...       ...   
284802 -2.606837 -4.918215  7.305334  1.914428  ...  1.475829  0.213454   
284803  1.058415  0.024330  0.294869  0.584800  ...  0.059616  0.214205   
284804  3.031260 -0.296827  0.708417  0.432454  ...  0.001396  0.232045   
284805  0.623708 -0.686180  0.679145  0.392087  ...  0.127434  0.265245   
284806 -0.649617  1.577006 -0.414650  0.486180  ...  0.382948  0.261057   

             V22       V23       V24       V25       V26       V27       V28  \
0       0.277838 -0.110474  0.066928  0.128539 -0.189115  0.133558 -0.021053   
1      -0.638672  0.101288 -0.339846  0.167170  0.125895 -0.008983  0.014724   
2       0.771679  0.909412 -0.689281 -0.327642 -0.139097 -0.055353 -0.059752   
3       0.005274 -0.190321 -1.175575  0.647376 -0.221929  0.062723  0.061458   
4       0.798278 -0.137458  0.141267 -0.206010  0.502292  0.219422  0.215153   
...          ...       ...       ...       ...       ...       ...       ...   
284802  0.111864  1.014480 -0.509348  1.436807  0.250034  0.943651  0.823731   
284803  0.924384  0.012463 -1.016226 -0.606624 -0.395255  0.068472 -0.053527   
284804  0.578229 -0.037501  0.640134  0.265745 -0.087371  0.004455 -0.026561   
284805  0.800049 -0.163298  0.123205 -0.569159  0.546668  0.108821  0.104533   
284806  0.643078  0.376777  0.008797 -0.473649 -0.818267 -0.002415  0.013649   

        Amount  
0       149.62  
1         2.69  
2       378.66  
3       123.50  
4        69.99  
...        ...  
284802    0.77  
284803   24.79  
284804   67.88  
284805   10.00  
284806  217.00  

[284807 rows x 30 columns]

In [7]:
y

0         0
1         0
2         0
3         0
4         0
         ..
284802    0
284803    0
284804    0
284805    0
284806    0
Name: Class, Length: 284807, dtype: int64

In [8]:
x = imb.iloc[:,:-1]
x

Time         V1         V2        V3        V4        V5  \
0            0.0  -1.359807  -0.072781  2.536347  1.378155 -0.338321   
1            0.0   1.191857   0.266151  0.166480  0.448154  0.060018   
2            1.0  -1.358354  -1.340163  1.773209  0.379780 -0.503198   
3            1.0  -0.966272  -0.185226  1.792993 -0.863291 -0.010309   
4            2.0  -1.158233   0.877737  1.548718  0.403034 -0.407193   
...          ...        ...        ...       ...       ...       ...   
284802  172786.0 -11.881118  10.071785 -9.834783 -2.066656 -5.364473   
284803  172787.0  -0.732789  -0.055080  2.035030 -0.738589  0.868229   
284804  172788.0   1.919565  -0.301254 -3.249640 -0.557828  2.630515   
284805  172788.0  -0.240440   0.530483  0.702510  0.689799 -0.377961   
284806  172792.0  -0.533413  -0.189733  0.703337 -0.506271 -0.012546   

              V6        V7        V8        V9  ...       V20       V21  \
0       0.462388  0.239599  0.098698  0.363787  ...  0.251412 -0.018307   
1      -0.082361 -0.078803  0.085102 -0.255425  ... -0.069083 -0.225775   
2       1.800499  0.791461  0.247676 -1.514654  ...  0.524980  0.247998   
3       1.247203  0.237609  0.377436 -1.387024  ... -0.208038 -0.108300   
4       0.095921  0.592941 -0.270533  0.817739  ...  0.408542 -0.009431   
...          ...       ...       ...       ...  ...       ...       ...   
284802 -2.606837 -4.918215  7.305334  1.914428  ...  1.475829  0.213454   
284803  1.058415  0.024330  0.294869  0.584800  ...  0.059616  0.214205   
284804  3.031260 -0.296827  0.708417  0.432454  ...  0.001396  0.232045   
284805  0.623708 -0.686180  0.679145  0.392087  ...  0.127434  0.265245   
284806 -0.649617  1.577006 -0.414650  0.486180  ...  0.382948  0.261057   

             V22       V23       V24       V25       V26       V27       V28  \
0       0.277838 -0.110474  0.066928  0.128539 -0.189115  0.133558 -0.021053   
1      -0.638672  0.101288 -0.339846  0.167170  0.125895 -0.008983  0.014724   
2       0.771679  0.909412 -0.689281 -0.327642 -0.139097 -0.055353 -0.059752   
3       0.005274 -0.190321 -1.175575  0.647376 -0.221929  0.062723  0.061458   
4       0.798278 -0.137458  0.141267 -0.206010  0.502292  0.219422  0.215153   
...          ...       ...       ...       ...       ...       ...       ...   
284802  0.111864  1.014480 -0.509348  1.436807  0.250034  0.943651  0.823731   
284803  0.924384  0.012463 -1.016226 -0.606624 -0.395255  0.068472 -0.053527   
284804  0.578229 -0.037501  0.640134  0.265745 -0.087371  0.004455 -0.026561   
284805  0.800049 -0.163298  0.123205 -0.569159  0.546668  0.108821  0.104533   
284806  0.643078  0.376777  0.008797 -0.473649 -0.818267 -0.002415  0.013649   

        Amount  
0       149.62  
1         2.69  
2       378.66  
3       123.50  
4        69.99  
...        ...  
284802    0.77  
284803   24.79  
284804   67.88  
284805   10.00  
284806  217.00  

[284807 rows x 30 columns]

In [9]:
y = imb.iloc[:,-1]
y

0         0
1         0
2         0
3         0
4         0
         ..
284802    0
284803    0
284804    0
284805    0
284806    0
Name: Class, Length: 284807, dtype: int64

# cross validation like KFold and Hyperparameter Tuning

In [10]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
from sklearn.model_selection import KFold

## Parameter And Hyperparameter tuning 

parameter and hyperparameter tuning is used to increase performance and accuracy of algorithms and models

Types of Hyper parameter tuning :-
1) GridSearchCV

2) RandomSearchCV

3) Keras Tuner

4) Bayesian optimization Hyperotu

5) Genetics Algorithms

6) optuna

In [11]:
num = 10.0**np.arange(-2,3)
num

array([1.e-02, 1.e-01, 1.e+00, 1.e+01, 1.e+02])

In [12]:
from sklearn.model_selection import GridSearchCV
log_class = LogisticRegression()
grid = {'C':num,'penalty':['l1','l2']}
cv = KFold(n_splits =5,random_state = None,shuffle =False)

In [13]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test= train_test_split(x,y,train_size = 0.7,test_size =0.3)

In [14]:
clf = GridSearchCV(log_class,grid,cv = cv,n_jobs = -1 , scoring = 'f1_macro')
clf.fit(x_train,y_train)

c:\users\ankit\appdata\local\programs\python\python38\lib\site-packages\sklearn\model_selection\_search.py:922: UserWarning: One or more of the test scores are non-finite: [       nan 0.83839019        nan 0.8505624         nan 0.84923249
        nan 0.85147581        nan 0.85920227]
  warnings.warn(
c:\users\ankit\appdata\local\programs\python\python38\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


GridSearchCV(cv=KFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': array([1.e-02, 1.e-01, 1.e+00, 1.e+01, 1.e+02]),
                         'penalty': ['l1', 'l2']},
             scoring='f1_macro')

In [15]:
y_pred = clf.predict(x_test)
print(confusion_matrix(y_test,y_pred))

[[85238    46]
 [   54   105]]


In [16]:
print(accuracy_score(y_test,y_pred))

0.9988296291094648


In [17]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85284
           1       0.70      0.66      0.68       159

    accuracy                           1.00     85443
   macro avg       0.85      0.83      0.84     85443
weighted avg       1.00      1.00      1.00     85443



In [18]:
y_train.value_counts()

0    199031
1       333
Name: Class, dtype: int64

In [19]:
class_weight = dict({0:1,1:100})
class_weight

{0: 1, 1: 100}

In [20]:
from sklearn.ensemble import RandomForestClassifier
rand_forest = RandomForestClassifier(class_weight = class_weight)
rand_forest.fit(x_train,y_train)

RandomForestClassifier(class_weight={0: 1, 1: 100})

In [21]:
y_pred = rand_forest.predict(x_test)
y_pred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [22]:
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[85280     4]
 [   46   113]]
0.9994148145547324
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85284
           1       0.97      0.71      0.82       159

    accuracy                           1.00     85443
   macro avg       0.98      0.86      0.91     85443
weighted avg       1.00      1.00      1.00     85443



# Under Sampling Technique

In [23]:
from collections import Counter
Counter(y_train)

Counter({0: 199031, 1: 333})

In [24]:
#first method for finding the resampling of x,y train data
from imblearn.under_sampling import RandomUnderSampler  
under_sampler = RandomUnderSampler()
x_train_res, y_train_res = under_sampler.fit_resample(x_train, y_train)
print('The number of classes before fit {}'.format(Counter(y_train)))
print('The number of classes after fit {}'.format(Counter(y_train_res)))

The number of classes before fit Counter({0: 199031, 1: 333})
The number of classes after fit Counter({0: 333, 1: 333})


In [25]:
#second method for finding the resampling of x,y train data
from imblearn.under_sampling import NearMiss
ns = NearMiss(0.8)
x_train_ns,y_train_ns = ns.fit_resample(x_train,y_train)
print('The number of classes before fit {}'.format(Counter(y_train)))
print('The number of classes after fit {}'.format(Counter(y_train_ns)))

c:\users\ankit\appdata\local\programs\python\python38\lib\site-packages\imblearn\utils\_validation.py:587: FutureWarning: Pass sampling_strategy=0.8 as keyword args. From version 0.9 passing these as positional arguments will result in an error
  warnings.warn(


The number of classes before fit Counter({0: 199031, 1: 333})
The number of classes after fit Counter({0: 416, 1: 333})


In [26]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier()
classifier.fit(x_train_res,y_train_res)

RandomForestClassifier()

In [27]:
y_pred = classifier.predict(x_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[82566  2718]
 [   17   142]]
0.967990356143862
              precision    recall  f1-score   support

           0       1.00      0.97      0.98     85284
           1       0.05      0.89      0.09       159

    accuracy                           0.97     85443
   macro avg       0.52      0.93      0.54     85443
weighted avg       1.00      0.97      0.98     85443



# over Sampling technique

In [28]:
from imblearn.over_sampling import RandomOverSampler

os = RandomOverSampler(0.75)
x_train_res,y_train_res = os.fit_resample(x_train,y_train)
print('The Number of classes before fit {}'.format(Counter(y_train)))
print('The number of classes after resampler/fit {}'.format(Counter(y_train_res)))

c:\users\ankit\appdata\local\programs\python\python38\lib\site-packages\imblearn\utils\_validation.py:587: FutureWarning: Pass sampling_strategy=0.75 as keyword args. From version 0.9 passing these as positional arguments will result in an error
  warnings.warn(


The Number of classes before fit Counter({0: 199031, 1: 333})
The number of classes after resampler/fit Counter({0: 199031, 1: 149273})


In [29]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier()
classifier.fit(x_train_res,y_train_res)

RandomForestClassifier()

In [30]:
y_pred = classifier.predict(x_test)
print(confusion_matrix(y_test,y_pred))

print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[85279     5]
 [   42   117]]
0.9994499256814484
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85284
           1       0.96      0.74      0.83       159

    accuracy                           1.00     85443
   macro avg       0.98      0.87      0.92     85443
weighted avg       1.00      1.00      1.00     85443



# SMOTETomek technique

In [31]:
from imblearn.combine import SMOTETomek

In [ ]:
smtk = SMOTETomek()
x_train_res , y_train_res = smtk.fit_sample(x_train,y_train)

print('The Number of classes before fit {}'.format(Counter(y_train)))

print('The Number of classes after fit/resample {}'.format(Counter(y_train_res)))

In [ ]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier()
classifier.fit(x_train_res,y_train_res)

In [ ]:
y_pred = classifier.predict(x_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classpfication_report(y_test,y_pred))

# EnsembleClassifier technique

In [32]:
from imblearn.ensemble import EasyEnsembleClassifier

In [33]:
easy = EasyEnsembleClassifier()
easy.fit(x_train,y_train)

EasyEnsembleClassifier()

In [34]:
y_pred = easy.predict(x_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[82693  2591]
 [   16   143]]
0.969488430883747
              precision    recall  f1-score   support

           0       1.00      0.97      0.98     85284
           1       0.05      0.90      0.10       159

    accuracy                           0.97     85443
   macro avg       0.53      0.93      0.54     85443
weighted avg       1.00      0.97      0.98     85443



# power BI jupyter

In [ ]:
#online run
from powerbiclient import Report, models

In [ ]:
# Import the DeviceCodeLoginAuthentication class to authenticate against Power BI
from powerbiclient.authentication import DeviceCodeLoginAuthentication

# Initiate device authentication
device_auth = DeviceCodeLoginAuthentication()

In [ ]:
group_id="c506d01b-b948-405a-8807-75f5f461e386"
report_id="6f173542-1ae0-4ec1-a05e-eb5ad544f15c"

In [ ]:
report = Report(group_id=group_id, report_id=report_id, auth=device_auth)

report